In [1]:
import pandas as pd

In [56]:
if __name__ == "__main__":
  print("Hello World")

Hello World

In [7]:
df = pd.read_excel("Schedule_aw.xlsx")

In [8]:
df.head()

       Name       Available Days Shift Preference Fulltime/Part-time    Tier
0      Arun  Mon,Tue,Wed,Thu,Fri          Morning           Fulltime  Tier 1
1   Christo      Mon,Tue,Wed,Thu            Night           Fulltime  Tier 1
2      Amal      Mon,Wed,Thu,Fri            Night          Part-time  Tier 2
3  Rishitha          Mon,Wed,Fri          Morning          Part-time  Tier 2
4     Ridhi          Tue,Thu,Fri          Evening          Part-time  Tier 2

In [104]:
df["Available Days"].apply(lambda x: [d.strip() for d in str(x).split(",")])

0     [Mon, Tue, Wed, Thu, Fri]
1          [Mon, Tue, Wed, Thu]
2          [Mon, Wed, Thu, Fri]
3               [Mon, Wed, Fri]
4               [Tue, Thu, Fri]
5     [Mon, Tue, Wed, Thu, Fri]
6                    [Tue, Wed]
7     [Mon, Tue, Wed, Thu, Fri]
8     [Mon, Tue, Wed, Thu, Fri]
9     [Mon, Tue, Wed, Thu, Fri]
10    [Mon, Tue, Wed, Thu, Fri]
11    [Mon, Tue, Wed, Thu, Fri]
12    [Mon, Tue, Wed, Thu, Fri]
13    [Mon, Tue, Wed, Thu, Fri]
14    [Mon, Tue, Wed, Thu, Fri]
15    [Mon, Tue, Wed, Thu, Fri]
16    [Mon, Tue, Wed, Thu, Fri]
17    [Mon, Tue, Wed, Thu, Fri]
18    [Mon, Tue, Wed, Thu, Fri]
19    [Mon, Tue, Wed, Thu, Fri]
20    [Mon, Tue, Wed, Thu, Fri]
21    [Mon, Tue, Wed, Thu, Fri]
Name: Available Days, dtype: object

In [54]:
for i in dict1:
  #print(i)
  #print(dict1[i])
  for j in dict1[i]:
    print(j)

abcs
hysu
hskhdskh
d
e
f
g

In [37]:
for each_person in df['Name']:
  print(each_person)
  print(df[df['Name'] == each_person]['Available Days'])
  print(df[df['Name'] == each_person]['Shift Preference'])
  print(df[df['Name'] == each_person]['Fulltime/Part-time'])
  if (df[df['Name'] == each_person]['Fulltime/Part-time'].item()) =='Fulltime':
    print('Fulltime')
  else:
    print('Part-time')

Arun
0    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
0    Morning
Name: Shift Preference, dtype: object
0    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime
Christo
1    Mon,Tue,Wed,Thu
Name: Available Days, dtype: object
1    Night
Name: Shift Preference, dtype: object
1    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime
Amal
2    Mon,Wed,Thu,Fri
Name: Available Days, dtype: object
2    Night
Name: Shift Preference, dtype: object
2    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Rishitha
3    Mon,Wed,Fri
Name: Available Days, dtype: object
3    Morning
Name: Shift Preference, dtype: object
3    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Ridhi
4    Tue,Thu,Fri
Name: Available Days, dtype: object
4    Evening
Name: Shift Preference, dtype: object
4    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Sneha
5    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
5    Evening
Name: Shift Preference, dtype: object
5    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime
Gurudeep
6    Tue,Wed
Name: Available Days, dtype: object
6    Night
Name: Shift Preference, dtype: object
6    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Person11
7    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
7    Morning
Name: Shift Preference, dtype: object
7    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime
person12
8    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
8    Evening
Name: Shift Preference, dtype: object
8    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Person12
9    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
9    Evening
Name: Shift Preference, dtype: object
9    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime
person13
10    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
10    Night
Name: Shift Preference, dtype: object
10    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Person13
11    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
11    Morning
Name: Shift Preference, dtype: object
11    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime
person14
12    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
12    Evening
Name: Shift Preference, dtype: object
12    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Person14
13    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
13    Evening
Name: Shift Preference, dtype: object
13    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime
person15
14    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
14    Night
Name: Shift Preference, dtype: object
14    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Person15
15    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
15    Morning
Name: Shift Preference, dtype: object
15    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime
person16
16    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
16    Evening
Name: Shift Preference, dtype: object
16    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Person16
17    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
17    Evening
Name: Shift Preference, dtype: object
17    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime
person17
18    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
18    Night
Name: Shift Preference, dtype: object
18    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Person17
19    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
19    Morning
Name: Shift Preference, dtype: object
19    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime
person18
20    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
20    Evening
Name: Shift Preference, dtype: object
20    Part-time
Name: Fulltime/Part-time, dtype: object
Part-time
Person18
21    Mon,Tue,Wed,Thu,Fri
Name: Available Days, dtype: object
21    Evening
Name: Shift Preference, dtype: object
21    Fulltime
Name: Fulltime/Part-time, dtype: object
Fulltime

In [109]:
t= []
for each_person in df['Name']:
  #print(each_person)
  #print(df[df['Name'] == each_person]['Available Days'])
  if (df[df['Name'] == each_person]['Fulltime/Part-time'].item()) =='Fulltime' and (df[df['Name'] == each_person]['Tier'].item()) =='Tier 1':
    #print(each_person)
    days_string = df[df['Name'] == each_person]['Available Days'].item()
    # Convert it to a list of individual days
    days_list = [d.strip() for d in days_string.strip("[]").replace("'", "").split(",")]

    print(len(days_list))        # Correct length: 5
    print(days_list)

5
['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
4
['Mon', 'Tue', 'Wed', 'Thu']
5
['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
5
['Mon', 'Tue', 'Wed', 'Thu', 'Fri']

In [106]:
print(s)
len(s)

['Mon,Tue,Wed,Thu,Fri']

1

In [6]:
import random

# Convert string fields to lists
employees = []
for _, row in df.iterrows():
    employees.append({
        "name": row["Name"],
        "available_days": [d.strip() for d in row["Available Days"].split(",")],
        "pref": row["Shift Preference"].lower(),
        "type": row["Fulltime/Part-time"].lower(),
        "assigned": 0  # to track how many shifts assigned
    })

# Create 63 shifts: 7 days × 2 shifts/day × 4.5 slots
days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
shift_times = {"morning": "6-2", "evening": "2-10", "night": "10-6"}
shifts = []
id = 1
for day in days:
    for pref, time in shift_times.items():
        for _ in range(3):  # 3 shifts per type per day (7×3×3 = 63)
            shifts.append({"id": f"S{id}", "day": day, "time": time, "type": pref})
            id += 1

# Assign shifts
schedule = []
for shift in shifts:
    candidates = [
        emp for emp in employees
        if shift["day"] in emp["available_days"]
        and (emp["pref"] == "any" or emp["pref"] == shift["type"])
        and ((emp["type"] == "fulltime" and emp["assigned"] < 5) or (emp["type"] == "part-time" and emp["assigned"] < 3))
    ]
    if candidates:
        selected = random.choice(candidates)
        selected["assigned"] += 1
        schedule.append({
            "Shift ID": shift["id"],
            "Day": shift["day"],
            "Time": shift["time"],
            "Shift Type": shift["type"],
            "Assigned To": selected["name"]
        })
    else:
        schedule.append({
            "Shift ID": shift["id"],
            "Day": shift["day"],
            "Time": shift["time"],
            "Shift Type": shift["type"],
            "Assigned To": "Unassigned"
        })

# Export schedule to CSV
schedule_df = pd.DataFrame(schedule)
schedule_df.to_csv("simple_schedule_output.csv", index=False)
print("Schedule saved to simple_schedule_output.csv")

Schedule saved to simple_schedule_output.csv

In [ ]:
ls

 Volume in drive C is OS
 Volume Serial Number is DCA0-1A52

 Directory of C:\Users\ARUN\Downloads\Scheduling app

04-07-2025  20:30    <DIR>          .
04-07-2025  20:11    <DIR>          ..
04-07-2025  20:22    <DIR>          .ipynb_checkpoints
04-07-2025  20:22            10,079 Schedule_aw.xlsx
04-07-2025  20:30             1,934 simple_schedule_output.csv
04-07-2025  20:30             7,006 Untitled.ipynb
               3 File(s)         19,019 bytes
               3 Dir(s)  58,195,374,080 bytes free

In [ ]:

# Load employee data from Excel
employees_raw = pd.read_excel("Schedule_aw.xlsx")

# Clean and structure data
employees = []
for _, row in employees_raw.iterrows():
    employees.append({
        "name": row["Name"],
        "available_days": [d.strip() for d in row["Available Days"].split(",")],
        "pref": row["Shift Preference"].lower(),
        "type": row["Fulltime/Part-time"].lower(),
        "assigned": 0
    })

# Define all possible shifts
shift_definitions = [
    ("6 AM - 2 PM", "morning", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]),
    ("7 AM - 3 PM", "morning", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]),
    ("8 AM - 4 PM", "day", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]),
    ("9 AM - 1 PM", "day", ["Tue", "Wed", "Thu", "Fri"]),
    ("2 PM - 10 PM", "evening", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]),
    ("3 PM - 11 PM", "evening", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]),
    ("4 PM - 12 PM", "evening", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]),
    ("7 PM - 2 AM", "night", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]),
    ("10 PM - 6 AM", "night", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]),
    ("11 PM - 7 AM", "night", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]),
    ("11 AM - 7 PM", "day", ["Sun"])
]

# Generate 63 shift slots from available definitions
shifts = []
shift_id = 1
for time, category, days_list in shift_definitions:
    for day in days_list:
        if len(shifts) < 63:
            shifts.append({"id": f"S{shift_id}", "day": day, "time": time, "type": category})
            shift_id += 1

# Assign shifts
schedule = []
for shift in shifts:
    # Find eligible candidates
    candidates = [
        emp for emp in employees
        if shift["day"] in emp["available_days"]
        and (emp["pref"] == "any" or emp["pref"] == shift["type"])
        and ((emp["type"] == "fulltime" and emp["assigned"] < 4) or (emp["type"] == "part-time" and emp["assigned"] < 3))
    ]
    if candidates:
        selected = random.choice(candidates)
        selected["assigned"] += 1
        schedule.append({
            "Shift ID": shift["id"],
            "Day": shift["day"],
            "Time": shift["time"],
            "Shift Type": shift["type"],
            "Assigned To": selected["name"]
        })
    else:
        schedule.append({
            "Shift ID": shift["id"],
            "Day": shift["day"],
            "Time": shift["time"],
            "Shift Type": shift["type"],
            "Assigned To": "Unassigned"
        })

# Export the schedule
schedule_df = pd.DataFrame(schedule)
schedule_df.to_csv("simple_schedule_output.csv", index=False)
print("Schedule saved to simple_schedule_output.csv")

Schedule saved to simple_schedule_output.csv

In [ ]:
# simple_schedule_excel.py
import pandas as pd
import random
from datetime import datetime
# Load employee data from Excel
employees_raw = pd.read_excel("Schedule_aw.xlsx")
# Clean and structure data
employees = []
for _, row in employees_raw.iterrows():
    employees.append({
        "name": row["Name"],
        "available_days": [d.strip() for d in row["Available Days"].split(",")],
        "pref": row["Shift Preference"].lower(),
        "type": row["Fulltime/Part-time"].lower(),
        "assigned": 0,
        "total_hours": 0
    })

# Define all possible shifts with durations (in hours)
shift_definitions = [
    ("6 AM - 2 PM", "morning", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], 8),
    ("7 AM - 3 PM", "morning", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], 8),
    ("8 AM - 4 PM", "day", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], 8),
    ("9 AM - 1 PM", "day", ["Tue", "Wed", "Thu", "Fri"], 4),
    ("2 PM - 10 PM", "evening", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], 8),
    ("3 PM - 11 PM", "evening", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], 8),
    ("4 PM - 12 PM", "evening", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], 8),
    ("7 PM - 2 AM", "night", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], 7),
    ("10 PM - 6 AM", "night", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], 8),
    ("11 PM - 7 AM", "night", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], 8),
    ("11 AM - 7 PM", "day", ["Sun"], 8)
]

# Generate 63 shift slots from available definitions
shifts = []
shift_id = 1
for time, category, days_list, duration in shift_definitions:
    for day in days_list:
        if len(shifts) < 63:
            shifts.append({"id": f"S{shift_id}", "day": day, "time": time, "type": category, "duration": duration})
            shift_id += 1

# Assign shifts
schedule = []
for shift in shifts:
    # Find eligible candidates
    candidates = [
        emp for emp in employees
        if shift["day"] in emp["available_days"]
        and (emp["pref"] == "any" or emp["pref"] == shift["type"])
        and ((emp["type"] == "fulltime" and emp["assigned"] < 4) or (emp["type"] == "part-time" and emp["assigned"] < 3))
    ]
    if candidates:
        selected = random.choice(candidates)
        selected["assigned"] += 1
        selected["total_hours"] += shift["duration"]
        schedule.append({
            "Shift ID": shift["id"],
            "Day": shift["day"],
            "Time": shift["time"],
            "Shift Type": shift["type"],
            "Hours": shift["duration"],
            "Assigned To": selected["name"]
        })
    else:
        schedule.append({
            "Shift ID": shift["id"],
            "Day": shift["day"],
            "Time": shift["time"],
            "Shift Type": shift["type"],
            "Hours": shift["duration"],
            "Assigned To": "Unassigned"
        })

# Export the schedule
schedule_df = pd.DataFrame(schedule)
schedule_df.to_csv("simple_schedule_output_V1.csv", index=False)
print("Schedule saved to simple_schedule_output.csv")

# Summarize hours per person and save
summary = pd.DataFrame([{ "Employee": emp["name"], "Total Hours": emp["total_hours"] } for emp in employees])
summary.to_csv("employee_total_hours.csv", index=False)
print("Total hours per employee saved to employee_total_hours.csv")

Schedule saved to simple_schedule_output.csv
Total hours per employee saved to employee_total_hours.csv